--- #YAML:1.0
name:               Algorithm-NGram
version:            0.5
abstract:           ~
author:
    - Mischa Spiegelmock <mspiegelmock@gmail.com>
license:            unknown
distribution_type:  module
configure_requires:
    ExtUtils::MakeMaker:  0
build_requires:
    ExtUtils::MakeMaker:  0
requires:
    Class::Accessor::Fast:  0
no_index:
    directory:
        - t
        - inc
generated_by:       ExtUtils::MakeMaker version 6.56
meta-spec:
    url:      http://module-build.sourceforge.net/META-spec-v1.4.html
    version:  1.4
